In [ ]:
#Numpy-Numerical python -- used DA,DS,ML,and AI
#-numerical cal
#-working eith arrays
#-mathematical operations
#-statistical cal
#-matrix oper
#-data manipluation
#-scientific computing

#pip install numpy -- to install numpy

In [ ]:
import numpy as np   #to check the version
print(np.__version__)

2.1.3


In [ ]:
import numpy as np
#1D -- array
a = [10,20,30,40,50] #data is in list--hetrogenous
n = (np.array(a)) #convert list into array
print(n)

#to check dimension
print(n.ndim)

print(n.shape)  #to check shape



[10 20 30 40 50]
1
(5,)


In [ ]:
#2D-array
arr = np.array([
    [10,20,30],
    [50,40,60]
])
print(arr)

print("-----------------------------")

print(arr.ndim)  #to check the dimension

print(arr.shape) #to check shape

print("-------------------------------------")

print(arr.reshape(2,3)) #-- for reshape

[[10 20 30]
 [50 40 60]]
-----------------------------
2
(2, 3)
-------------------------------------
[[10 20 30]
 [50 40 60]]


In [ ]:
#3D array
arr = np.array([[
    [1,2,3],
    [4,5,6]],
  [
      [7,8,9],
      [2,4,5]
  ]
])

print(arr)

print("------------------------------------------------")

print(arr.ndim) #to check dimension

print("------------------------------------------------------------")

print(arr.dtype)  #to check the datatype

print("------------------------------------------------------------")

print(arr.shape)  #to check shape

print("-------------------------------------------------------------")

print(arr.reshape(2,3,2))  #reshape

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [2 4 5]]]
------------------------------------------------
3
------------------------------------------------------------
int64
------------------------------------------------------------
(2, 2, 3)
-------------------------------------------------------------
[[[1 2]
  [3 4]
  [5 6]]

 [[7 8]
  [9 2]
  [4 5]]]


In [ ]:
a = np.array(["isha","priya","arun"])
print(a.dtype)   #unicode/string -- it doesnt show is as string but its string

<U5


In [ ]:
#specifying datatype -- we cnvrt the dtype  -- it behaves like homogenous
arr = np.array([10,12,54], dtype = "float")
print(arr)
print(arr.dtype)

print("-----------------------------------------------")

arr = np.array([10,12,54], dtype = "int")
print(arr)
print(arr.dtype)



[10. 12. 54.]
float64
-----------------------------------------------
[10 12 54]
int64


In [ ]:
import array as arr  #-- another way to create an array
arr = arr.array('i',[1,2,3])
print(arr)

array('i', [1, 2, 3])


In [ ]:
#np.arange -- to generate the seq of num
arr = np.arange(1,10)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [ ]:
#np.range
arr = np.arange(1,11,2) #start,stop,step
print(arr)

[1 3 5 7 9]


In [ ]:
#for single array
import numpy as np
#np.zeros() -- to genreate n no.of zeros
arr = np.zeros(7)
print(arr)

#to get ones
arr= np.ones(5)
print(arr)

#to get any no we use full 5-no of repeations , 10 - no
arr=np.full(5,10)
print(arr)

[0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[10 10 10 10 10]


In [ ]:

#for zero
#2D
import numpy as np
arr = np.zeros((2,3))
print(arr)
print("----------------------------------")

#3D
#for ones
arr = np.ones((2,2,3))
print(arr)
print("------------------------------------")

#for any no -- 2D
arr = np.full((2,3),6)
print(arr)

print("---------------------------------------")

#for 3D array --full
arr = np.full((2,3,3),10)
print(arr)


[[0. 0. 0.]
 [0. 0. 0.]]
----------------------------------
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
------------------------------------
[[6 6 6]
 [6 6 6]]
---------------------------------------
[[[10 10 10]
  [10 10 10]
  [10 10 10]]

 [[10 10 10]
  [10 10 10]
  [10 10 10]]]


In [ ]:
#reshape--change the structure of an arr without changing its data
arr = [1,2,3,4,5,6,7]
arr = np.arange(1,7)
print(arr)
print("-------------------------------------")
new_arr = arr.reshape(2,3) #2-col,3-rows
print(new_arr)
print("-----------------------------------------")
new_arr = arr.reshape(3,2)
print(new_arr)


[1 2 3 4 5 6]
-------------------------------------
[[1 2 3]
 [4 5 6]]
-----------------------------------------
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
#identity Matrix --the diagonal elements are 1,rem = 0
#np.eye -- square matrix

arr= np.eye(4)
print(arr)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#numpy random package
#1D arr
arr = np.random.random(5) #float values  from 0 to 1 -- gives diff values when we run it
print(arr)

print("---------------------------------------------")

#2D arr
arr = np.random.random((2,3))
print(arr)
print("--------------------------------------------------")

#3D arr
arr = np.random.random((2,3,2))
print(arr)
print("-------------------------------------------------")

arr = np.random.randint(3)
print(arr)


[0.30471261 0.90217501 0.95915756 0.55020644 0.12180922]
---------------------------------------------
[[0.34486832 0.88102327 0.84823163]
 [0.35562153 0.42934567 0.95012602]]
--------------------------------------------------
[[[0.16011844 0.22830774]
  [0.45534453 0.59808398]
  [0.27944143 0.34484813]]

 [[0.15750325 0.46702552]
  [0.20856647 0.49630022]
  [0.6931509  0.13614885]]]
-------------------------------------------------
1


In [ ]:
#random.uniform() -- generete random values ,0-n, low,high,size
#np.random.uniform(low,high,size)

#1D
arr = np.random.uniform(12,24,7)
print(arr)
print('-----------------------------------')
#2D
arr = np.random.uniform(10,23,(2,3))
print(arr)

print('-------------------------------------')
#3D
arr = np.random.uniform(23,45,(2,3,2))
print(arr)

[23.85491871 19.75541065 16.03027581 23.64184563 20.26974885 13.25109635
 19.81658327]
-----------------------------------
[[10.43813677 13.04659279 14.65898207]
 [11.76581358 15.14113864 11.72499608]]
-------------------------------------
[[[27.22075477 36.29436943]
  [34.83882343 42.80493775]
  [40.18914394 32.08840456]]

 [[32.81195494 36.73106793]
  [32.32505747 35.52901525]
  [30.49223542 34.44497247]]]


In [ ]:
#random.randn()--lies btwn 0 and 1
#mean = 0, stdv = 1 --use for neg,pos,close to zero
#1D
arr = np.random.randn(5)
print(arr)

print('-------------------------------------------')

#2D
arr = np.random.randn(2,5)
print(arr)

print("-------------------------------------------")

#3D
arr = np.random.randn(2,3,2)
print(arr)

[ 0.8945363  -0.23957315 -0.09414466 -2.25223027 -1.16744855]
-------------------------------------------
[[ 0.37975738  1.65892623 -2.61691184 -0.88630687 -2.00532032]
 [-0.79726982  0.49813125  1.25274685 -1.80335802 -1.96821314]]
-------------------------------------------
[[[ 1.00861393  1.12552982]
  [ 0.65550579 -0.56207664]
  [-0.09335148  0.81238337]]

 [[ 1.23988875  0.58983784]
  [-0.00733052 -1.78489792]
  [-0.88246627  0.70996414]]]


In [ ]:
#choice -- random select values from an arr or seq -- it randomly select the value which we given
arr = np.array([10,20,30,40,50])
n = np.random.choice(arr)
print(n)

print("-----------------------------------------")

arr = np.array([10,20,30,40,50])
n = np.random.choice(arr,3) #get 3 values
print(n)

print("-----------------------------------------")
arr =np.array(["lisa","isha","sweety","tina","rosey"])
n = np.random.choice(arr)
print(n)

print("--------------------------------------------")

#we get more than 1 values if we keep arr,4
arr =np.array(["lisa","isha","sweety","tina","rosey"])
n = np.random.choice(arr,4)
print(n)

10
-----------------------------------------
[10 20 10]
-----------------------------------------
tina
--------------------------------------------
['tina' 'lisa' 'tina' 'tina']


In [ ]:
#choice()-- with probability
arr = [10,20,30]
res = np.random.choice(
    arr,
    size = 7,
    p = [0.2,0.5,0.3] #prob should be 1
)
print(res)

[20 30 20 10 20 30 20]


In [ ]:
#seed() - fixed evrytime same value
arr = np.random.random(10)
np.random.seed(10)  #seed doesnt generate no so we use random.random ,Seed helps to save the generate num
print(arr)

[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665
 0.19806286 0.76053071 0.16911084 0.08833981]


In [ ]:
#randint --- it generte one no from 3-10
arr = np.random.randint(3,10)
print(arr)

3


In [ ]:
#shuffle --- give an diff order rather than existing value,original arr remains same but only order changes
import numpy as np
n =([10,20,30,40,50])
np.random.shuffle(n)
print(n)

[40, 10, 50, 30, 20]


In [ ]:
#permutation()- #doesnt change its originally array , duplicate  array change when  we excute it
arr = np.array([10,20,30,40,50])
print(arr)
res = np.random.permutation(arr)
print(res)

[10 20 30 40 50]
[20 10 40 30 50]


In [ ]:
#np.linspace() #-- for linespace -- equally sprt with spaces num btwn starting and ending number -- it generate floating numbers,space along with the step
#starting - 0
#ending - 10
#num of values - 5
import numpy as np
arr = np.linspace(0,10,5)
print(arr)


[ 0.   2.5  5.   7.5 10. ]


In [ ]:
#ravel - convert 2D arr into single dim arr
arr = np.array([[1,2],
                [3,4]])
print(arr)
print("-----------------------------------------")
arr = np.ravel(arr)
print(arr)

[[1 2]
 [3 4]]
-----------------------------------------
[1 2 3 4]


In [ ]:
#transpose - arr.T cnvrt rows - col,col-rows
arr = np.array([[1,2],
                [3,4]])
print(arr)

print("---------------------------------------")

n = arr.T
print(n)



[[1 2]
 [3 4]]
---------------------------------------
[[1 3]
 [2 4]]


In [ ]:
#shape - attribute
#size  - teels us total no of elemts -- attribute
arr = np.array([
    [10,20,30],
    [40,50,60]
])
print(arr.size)

6


In [ ]:
#astype -- cnvrt 1 daratype to another
arr = np.array([10,20,30],dtype = "int")
print(arr)
new_arr = arr.astype(float)
print(new_arr)

[10 20 30]
[10. 20. 30.]


In [ ]:
#indexing
arr = np.array([10,20,30,40,50])
print(arr[0])
print(arr[5:]) #to get after 5 element
#slicing
print(arr[0:3])
print(arr[-1]) # -- to get last 1 element
print(arr[-3:-1])

10
[10 20 30]
50
[30 40]


In [ ]:
#indexing - 2D arr
arr = np.array([
    [10,20,30],
    [34,56,7]

])
print(arr[(1,2)])

print("-------------------------------------")

#3D array
arr = np.array([
    [10,20,30],
    [34,56,7],
    [3,45,22]

])
print(arr[(1,2),(2,2)])

print("----------------------------------------")

print(arr[0:1])

7
-------------------------------------
[ 7 22]
----------------------------------------
[[10 20 30]]


In [ ]:
#silicing
#3D array
arr = np.array([
    [10,20,30],
    [34,56,7],
    [3,45,22]

])
print(arr[0:1])

[[10 20 30]]


In [ ]:
#modification --
#1D

arr = np.array([10,20,100,30,40])
arr [0:3] = 99
print(arr)
print("-------------------------------")
#2D

arr = np.array([
    [10,20,30],
    [34,56,7]
])
arr[0,1] = 200
print(arr)



[99 99 99 30 40]
-------------------------------
[[ 10 200  30]
 [ 34  56   7]]


In [ ]:
#insert --np.insert()
arr = np.array([10,20,30,40,50])
new_arr = np.insert(arr,2,100)  #2 posi- insert 100
print(new_arr)

print("----------------------------------")

arr = np.array([10,20,30,40,50])
new_arr = np.insert(arr,2,[100,200])  #for multiple numbers
print(new_arr)

[ 10  20 100  30  40  50]
----------------------------------
[ 10  20 100 200  30  40  50]


In [ ]:
#delete--np.delete
arr = np.array([10,20,30,40,50])
new_arr = np.delete(arr,2)
print(new_arr)

print("-----------------------------------")

arr = np.array([10,20,30,40,50])
new_arr = np.delete(arr,[2,3])  #for multiple values -- index based removing
print(new_arr)


[10 20 40 50]
-----------------------------------
[10 20 50]


In [ ]:
#1D - arr(insert & DElete)
import numpy as np
arr = np.array([10,20,30,40,50])
new_arr = np.insert(arr,2,25)   #to insert
print(new_arr)

n = np.delete(new_arr,2)  #to delete element at index 2
print(n)

#del elements at index 1 and 3
n = np.delete(new_arr,[1,3])
print(n)


[10 20 25 30 40 50]
[10 20 30 40 50]
[10 25 40 50]


In [ ]:
#2D - array -- insert
arr = np.array([[1,2],
                [3,4]
                ])
n = np.insert(arr,1,[6,7],axis = 0)  # 0 -row
print(n)

print("-------------------------------------------------")

arr = np.array([[1,2],
                [3,4]
                ])
n = np.insert(arr,2,[6,7],axis = 1)  # 1 -col
print(n)



[[1 2]
 [6 7]
 [3 4]]
-------------------------------------------------
[[1 2 6]
 [3 4 7]]


In [ ]:
#2D----Delete
arr = np.array([[1,2],
                [3,4],
                [6,7]
                ])
n = np.delete(arr,1,axis = 0)  # 0 -row
print(n)

print('-------------------------------------------')


arr = np.array([[1,2,6],
                [3,4,8]
                ])
n = np.delete(arr,1,axis = 1)  # 1 -col
print(n)



[[1 2]
 [6 7]]
-------------------------------------------
[[1 6]
 [3 8]]


In [ ]:
#aggeration functions in numpy
#sum
#1D-array
arr = np.array([10,20,30,40,50,60])
print(np.sum(arr))

print("--------------------------------")

#2d array
arr = np.array([[1,2],
                [3,4],
                [5,6]])
print(np.sum(arr,axis = 0))
print(np.sum(arr,axis = 1))




210
--------------------------------
[ 9 12]
[ 3  7 11]


In [ ]:
#max
arr = np.array([10,20,30,40,50,60])
print(np.max(arr))

print("-------------------------------------")

arr = np.array([[1,2],
                [3,4],
                [5,6]])
print(np.max(arr,axis = 0))
print(np.max(arr,axis = 1))


60
-------------------------------------
[5 6]
[2 4 6]


In [ ]:
#min
arr = np.array([10,20,30,40,50,60])
print(np.min(arr))

print("-------------------------------------")

arr = np.array([[1,2],
                [3,4],
                [5,6]])
print(np.min(arr,axis = 0))
print(np.min(arr,axis = 1))

10
-------------------------------------
[1 2]
[1 3 5]


In [ ]:
#mean
arr = np.array([10,20,30,40,50,60])
print(np.mean(arr))

print("-------------------------------------")

arr = np.array([[1,2],
                [3,4],
                [5,6]])
print(np.mean(arr,axis = 0))
print(np.mean(arr,axis = 1))

35.0
-------------------------------------
[3. 4.]
[1.5 3.5 5.5]


In [ ]:
#var
arr = np.array([10,20,30,40,50,60])
print(np.var(arr))

print("-------------------------------------")

arr = np.array([[1,2],
                [3,4],
                [5,6]])
print(np.var(arr,axis = 0))
print(np.var(arr,axis = 1))

291.6666666666667
-------------------------------------
[2.66666667 2.66666667]
[0.25 0.25 0.25]


In [ ]:
#std()
arr = np.array([10,20,30,40,50,60])
print(np.std(arr))

print("-------------------------------------")

arr = np.array([[1,2],
                [3,4],
                [5,6]])
print(np.std(arr,axis = 0))
print(np.std(arr,axis = 1))

17.07825127659933
-------------------------------------
[1.63299316 1.63299316]
[0.5 0.5 0.5]


In [ ]:
#percentile()--highest value in our arr - it count with it,think highest value in given list,0-100 range
arr = np.array([10,20,30,40,50,60])
print(np.percentile(arr,60))

print("-------------------------------------")

arr = np.array([10,20,30,40,50,60]) #multiple values
print(np.percentile(arr,[60,50]))

print("----------------------------------")

arr = np.array([[1,2],
                [3,4],
                [5,6]])
print(np.percentile(arr,6,axis = 0))
print(np.percentile(arr,6,axis = 1))


40.0
-------------------------------------
[40. 35.]
----------------------------------
[1.24 2.24]
[1.06 3.06 5.06]


In [ ]:
#quantile() --range 0 to 1, should be in float or percentage
arr = np.array([10,20,30,40,50,60])
print(np.quantile(arr,0.60))

print("------------------------------------")

arr = np.array([[1,2],
                [3,4],
                [5,6]])
print(np.quantile(arr,0.60,axis = 0))
print(np.quantile(arr,0.60,axis = 1))


40.0
------------------------------------
[3.4 4.4]
[1.6 3.6 5.6]


In [ ]:
#argmax()--index position of the largest
arr = np.array([10,20,30,40,50,60])
print(np.argmax(arr))

print("-------------------------------------")

arr = np.array([[1,2],
                [3,4],
                [5,6]])
print(np.argmax(arr,axis = 0))
print(np.argmax(arr,axis = 1))

5
-------------------------------------
[2 2]
[1 1 1]


In [ ]:
#argmin()
arr = np.array([10,20,30,40,50,60])
print(np.argmin(arr))

print("-------------------------------------")

arr = np.array([[1,2],
                [3,4],
                [5,6]])
print(np.argmin(arr,axis = 0))
print(np.argmin(arr,axis = 1))

0
-------------------------------------
[0 0]
[0 0 0]


In [ ]:
#log10 , value in array, base log10
arr = np.array([10,100,1000])
print(np.log10(arr))

[1. 2. 3.]


In [ ]:
#log2
arr = np.array([2,4,6,9])
print(np.log2(arr))

[1.        2.        2.5849625 3.169925 ]


In [ ]:
#log() -- em power evakapote base e tesukuntdhi (e=2.71828)
arr = np.array([1,2,10])
print(np.log(arr))

[0.         0.69314718 2.30258509]


In [ ]:
#sqrt()
arr = np.array([4,9,16,25])
print(np.sqrt(arr))

arr = np.array([121])
print(np.sqrt(arr))



[2. 3. 4. 5.]
[11.]


In [ ]:
#round -- decimal values  5 abv - highest, 5-blw-least
arr = np.array([10.723,10.4,20.3644,30,45])
print(np.round(arr))

#specify decimal places

arr = np.array([10.7,10.4,20.36,30.45])
print(np.round(arr,2))  #change 3 digit

[11. 10. 20. 30. 45.]
[10.7  10.4  20.36 30.45]


In [ ]:
import numpy as np
#floor - least num
arr = np.array([10.7,10.4,20.36,30.45])
print(np.floor(arr))

[10. 10. 20. 30.]


In [ ]:
#ceil - highest values
arr = np.array([10.7,10.4,20.36,30.45])
print(np.ceil(arr))


[11. 11. 21. 31.]


In [ ]:
#abs()--restuen absolute value--it returns postive numbs
arr = np.array([10,-3,-4,0,-5,-8])
print(np.abs(arr))



[10  3  4  0  5  8]


In [ ]:
#sorting integer array  -- ascending order
arr = np.array([50,10,20,30,40])
result = np.sort(arr)
print(result)

[10 20 30 40 50]


In [ ]:
#sorting integer array  -- descending order
arr = np.array([50,10,20,30,40])
result = np.sort(arr)[::-1]
print(result)

[50 40 30 20 10]


In [ ]:
#numpy-concetenation & stacking -- combining two or more numpy arrays into a single array
#np.concatenate()  -- joins array along an existing
#np.stack()

#np.concatenate()-- no change in dim
import numpy as np
arr1 = np.array([10,20,30])
arr2 = np.array([40,50,60])
res = np.concatenate((arr1,arr2))
print(res)

[10 20 30 40 50 60]


In [ ]:
#the reshape should be same ortherwise we get an error
#2D
arr = np.arange(10,20).reshape(2,5)
arr3 = np.arange(1,11).reshape(5,2)
print(arr)
print(arr3)
arr4=np.concatenate((arr,arr3))

[[10 11 12 13 14]
 [15 16 17 18 19]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 5 and the array at index 1 has size 2

In [ ]:
#2D
arr = np.arange(10,20).reshape(2,5)  #for 2 dim the shoul be same
arr3 = np.arange(1,11).reshape(2,5)
print(arr)
print(arr3)
arr4=np.concatenate((arr,arr3))

print("------------------------------------------------------")

#3d

arr = np.arange(10,20).reshape(2,5,1)  #for 3 dim the shoul be same
arr3 = np.arange(1,11).reshape(2,5,1)
print(arr)
print(arr3)
arr4=np.concatenate((arr,arr3))





[[10 11 12 13 14]
 [15 16 17 18 19]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
------------------------------------------------------
[[[10]
  [11]
  [12]
  [13]
  [14]]

 [[15]
  [16]
  [17]
  [18]
  [19]]]
[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]]]


In [ ]:
#horizontal --side by side, two arr should hv same arr
arr1 = np.array([[10,20,30],
                [40,50,60]])
arr2 = np.array([[30,50,40],
                 [90,70,10]])
print(np.concatenate((arr1,arr2),axis = 1)) #col

[[10 20 30 30 50 40]
 [40 50 60 90 70 10]]


In [ ]:
#vertical -- row wise
arr1 = np.array([[10,20],
                [40,50]])
arr2 = np.array([[30,50],
                 [90,70]])
print(np.concatenate((arr1,arr2),axis = 0)) #row


[[10 20]
 [40 50]
 [30 50]
 [90 70]]


In [ ]:
#np.stack()--dim no change,
#1d
arr1 = np.array([10,20,30])
arr2 = np.array([50,40,60])
res = np.concatenate((arr1,arr2),axis = 0)
print(res)
print(res.ndim)

print("----------------------------------------------------")

#stack - new dim is created
#1d
arr1 = np.array([10,20,30])
arr2 = np.array([50,40,60])
res = np.stack((arr1,arr2),axis = 0)
print(res)
print(res.ndim)

print("--------------------------------------------")

#2D
arr = np.arange(10,20).reshape(2,5)
arr3 = np.arange(1,11).reshape(2,5)
print(arr)
print(arr3)
arr4=np.stack((arr,arr3))
print(arr4.ndim)

print("--------------------------------------------------")

#3d

arr = np.arange(10,20).reshape(2,5,1)
arr3 = np.arange(1,11).reshape(2,5,1)
print(arr)
print(arr3)
arr4=np.stack((arr,arr3))
print(arr4.ndim)



[10 20 30 50 40 60]
1
----------------------------------------------------
[[10 20 30]
 [50 40 60]]
2
--------------------------------------------
[[10 11 12 13 14]
 [15 16 17 18 19]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
3
--------------------------------------------------
[[[10]
  [11]
  [12]
  [13]
  [14]]

 [[15]
  [16]
  [17]
  [18]
  [19]]]
[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]]]
4


In [ ]:
#v-stack() --
#1d
arr1 = np.array([10,20,30])
arr2 = np.array([50,40,60])
res = np.vstack((arr1,arr2))
print(res)
print(res.ndim)


print("--------------------------------------------")

arr1 = np.array([10,20,30])
arr2 = np.array([50,40,60])
arr3 = np.array([34,56,78])
res = np.vstack((arr1,arr2,arr3))
print(res)
print(res.ndim)

print("-----------------------------------------------")

#2D
arr = np.arange(10,20).reshape(2,5)
arr3 = np.arange(1,11).reshape(2,5)
print(arr)
print(arr3)
arr4=np.vstack((arr,arr3))
print(arr4.ndim)


print("--------------------------------------------------")

#3d

arr = np.arange(10,20).reshape(2,5,1)
arr3 = np.arange(1,11).reshape(2,5,1)
print(arr)
print(arr3)
arr4=np.vstack((arr,arr3))
print(arr4.ndim)





[[10 20 30]
 [50 40 60]]
2
--------------------------------------------
[[10 20 30]
 [50 40 60]
 [34 56 78]]
2
-----------------------------------------------
[[10 11 12 13 14]
 [15 16 17 18 19]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2
--------------------------------------------------
[[[10]
  [11]
  [12]
  [13]
  [14]]

 [[15]
  [16]
  [17]
  [18]
  [19]]]
[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]]]
3


In [ ]:
#H-stack() -- horizontal - side by side
#1d
arr1 = np.array([10,20,30])
arr2 = np.array([50,40,60])
res = np.hstack((arr1,arr2))
print(res)
print(res.ndim)

print("----------------------------------------")

arr1 = np.array([10,20,30])
arr2 = np.array([50,40,60])
arr3 = np.array([34,56,78])
res = np.hstack((arr1,arr2,arr3))
print(res)
print(res.ndim)


print("--------------------------------------------")

#2D
arr = np.arange(10,20).reshape(2,5)
arr3 = np.arange(1,11).reshape(2,5)
print(arr)
print(arr3)
arr4=np.hstack((arr,arr3))
print(arr4.ndim)


print("--------------------------------------------------")

#3d

arr = np.arange(10,20).reshape(2,5,1)
arr3 = np.arange(1,11).reshape(2,5,1)
print(arr)
print(arr3)
arr4=np.hstack((arr,arr3))
print(arr4.ndim)

[10 20 30 50 40 60]
1
----------------------------------------
[10 20 30 50 40 60 34 56 78]
1
--------------------------------------------
[[10 11 12 13 14]
 [15 16 17 18 19]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2
--------------------------------------------------
[[[10]
  [11]
  [12]
  [13]
  [14]]

 [[15]
  [16]
  [17]
  [18]
  [19]]]
[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]]]
3
