In [ ]:
import numpy as np
arr = [10,15,20,25,30,35,40,45,50]
np.array(arr)
print(arr)
print('--------------------------------------')
#or

arr = np.arange(10,50,5)
print(arr)

[10, 15, 20, 25, 30, 35, 40, 45, 50]
--------------------------------------
[10 15 20 25 30 35 40 45]


In [ ]:
arr = np.arange(2,30,2)
print(arr)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28]


In [ ]:
arr = np.arange(1001,1021)
print(arr)

[1001 1002 1003 1004 1005 1006 1007 1008 1009 1010 1011 1012 1013 1014
 1015 1016 1017 1018 1019 1020]


In [ ]:
arr = np.arange(50,0,-1)
print(arr)

[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3
  2  1]


In [ ]:
arr =np.array ([[[1,2,4],
       [1,4,2],
       [2,1,4]],

       [[2,4,1],
       [4,1,2],
       [4,2,1]],

         [[1,1,8],
          [1,8,1],
          [8,1,1]]])
print(arr)


[[[1 2 4]
  [1 4 2]
  [2 1 4]]

 [[2 4 1]
  [4 1 2]
  [4 2 1]]

 [[1 1 8]
  [1 8 1]
  [8 1 1]]]


In [ ]:
arr = np.array([101,102,103,104,105,106,107,108])
np.random.shuffle(arr)
print(arr)

[106 103 105 104 107 102 101 108]


In [ ]:
emp = np.array(["ravi","priya","arun","sneha","kiran"])
np.random.shuffle(emp)
print(emp)

['arun' 'priya' 'kiran' 'ravi' 'sneha']


In [ ]:
num = np.array([10,20,30,40,50])
print(num)
arr = np.random.permutation(num)
print(arr)

[10 20 30 40 50]
[50 10 40 30 20]


In [ ]:
arr = np.arange(1,25)
print(arr)

print("-----------------------------------")

n = arr.reshape(4,6)
print(n)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
-----------------------------------
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [ ]:
arr = np.arange(1,21)
print(arr)

print("---------------------------------------------------")

n = arr.reshape(4,5)
print(n)

print('---------------------------------------')

print(n.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
---------------------------------------------------
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
---------------------------------------
(4, 5)


In [ ]:
#2.questions
#1 create numpy arr 1d
import numpy as np
arr = np.array([10,20,30,40,50])
print(arr)
print(arr.dtype)
print(arr.ndim)
print(arr.shape)

[10 20 30 40 50]
int64
1
(5,)


In [ ]:
#2.1d array of 5 zeros
arr = np.zeros(5)
print(arr)

print("--------------------------------")

arr = np.zeros((3,4))
print(arr)

print("----------------------------")

arr = np.zeros((2,3,4))
print(arr)

[0. 0. 0. 0. 0.]
--------------------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
----------------------------
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [ ]:
#3
n = np.ones(5)
print(n)
print(n.ndim)

print("----------------------------------------")

n = np.ones((2,3))
print(n)
print(n.ndim)

print("------------------------------------")

n = np.ones((2,2,3))
print(n)
print(n.ndim)

[1. 1. 1. 1. 1.]
1
----------------------------------------
[[1. 1. 1.]
 [1. 1. 1.]]
2
------------------------------------
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
3


In [ ]:
#4.
n = np.full((4,5),1000)
print(n)
print(n.shape)
print(n.ndim)
print(n.dtype)


[[1000 1000 1000 1000 1000]
 [1000 1000 1000 1000 1000]
 [1000 1000 1000 1000 1000]
 [1000 1000 1000 1000 1000]]
(4, 5)
2
int64


In [ ]:
arr = np.eye(5,5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
arr = np.arange(101,121)
print(arr)
print('------------------------------------')
n = np.random.permutation(arr)
print(n)
print("-----------------------------------------")
np.random.shuffle(arr)
print(arr)


[101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118
 119 120]
------------------------------------
[116 114 110 104 120 112 117 119 103 102 109 101 111 118 113 106 108 105
 115 107]
-----------------------------------------
[113 108 103 112 102 119 104 120 111 110 118 105 106 116 109 117 101 115
 114 107]


In [ ]:
arr = np.arange(1,11)
print(arr)
n = np.random.permutation(arr)
print(n)

[ 1  2  3  4  5  6  7  8  9 10]
[ 8  5  6  3  4  2 10  9  7  1]


In [ ]:
arr = np.arange(1,25)
print(arr)
print(arr.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
(24,)


In [ ]:
n = np.random.uniform(0,1,10)
print(n)
print("------------------------------------")
n = n.reshape(2,5)
print(n)

print("-------------------------------------------")
n =n.reshape(2,1,5)
print(n)

[0.00252053 0.39811387 0.59470212 0.16050195 0.61789547 0.83527668
 0.72423691 0.68416103 0.20113537 0.0408367 ]
------------------------------------
[[0.00252053 0.39811387 0.59470212 0.16050195 0.61789547]
 [0.83527668 0.72423691 0.68416103 0.20113537 0.0408367 ]]
-------------------------------------------
[[[0.00252053 0.39811387 0.59470212 0.16050195 0.61789547]]

 [[0.83527668 0.72423691 0.68416103 0.20113537 0.0408367 ]]]


In [ ]:
arr = np.random.uniform(50,100,10)
print(arr)

[55.65948543 64.63337193 53.26316153 86.27956061 89.62705616 77.20488666
 70.46353929 79.5539652  50.90812189 86.99555345]


In [ ]:
#HW
import numpy as np

# 1. Sum of all elements
arr = np.array([10, 20, 30, 40, 50])
print(np.sum(arr))

print("----------------------------------------------------------")


# 2. Minimum and Maximum
marks = np.array([45, 78, 92, 56, 88, 67, 34])
print("2. Minimum:", np.min(marks))
print("   Maximum:", np.max(marks))


print("----------------------------------------------------------")

# 3. Average sales
sales = np.array([12000, 15000, 18000, 11000, 20000])
print("3. Average sales:", np.mean(sales))

print("----------------------------------------------------------")

# 4. Variance
data = np.array([10, 20, 30, 40, 50])
print("4. Variance:", np.var(data))

print("----------------------------------------------------------")

# 5. Standard deviation
marks = np.array([60, 70, 80, 90, 100])
print("5. Standard deviation:", np.std(marks))

print("----------------------------------------------------------")

# 6. 50th percentile
marks = np.array([35, 42, 55, 60, 68, 72, 80, 85, 95, 100])
print("6. 50th percentile:", np.percentile(marks, 50))

print("----------------------------------------------------------")

# 7. 25th and 75th percentiles
salary = np.array([25000, 30000, 35000, 40000, 45000, 50000])
print("7. 25th percentile:", np.quantile(salary, 0.25))
print("   75th percentile:", np.quantile(salary, 0.75))


print("----------------------------------------------------------")
# 8. Index of highest sales
sales = np.array([15000, 22000, 18000, 35000, 27000, 12000])
print("8. Index of highest sales:", np.argmax(sales))

print("----------------------------------------------------------")

# 9. Index of lowest temperature
temperatures = np.array([32, 28, 35, 25, 30, 22, 38])
print("9. Index of lowest temperature:", np.argmin(temperatures))

print("----------------------------------------------------------")

# 10. Base-10 logarithm
arr = np.array([1, 10, 100, 1000, 10000])
print("10. Base-10 logarithm:", np.log10(arr))

print("----------------------------------------------------------")

# 11. Base-2 logarithm
arr = np.array([1, 2, 4, 8, 16, 32])
print("11. Base-2 logarithm:", np.log2(arr))


print("----------------------------------------------------------")

# 12. Natural logarithm
arr = np.array([1, 2, 3, 4, 5])
print("12. Natural logarithm:", np.log(arr))


print("----------------------------------------------------------")
# 13. Square root
arr = np.array([4, 9, 16, 25, 36, 49])
print("13. Square root:", np.sqrt(arr))

print("----------------------------------------------------------")

# 14. Round to nearest integer
prices = np.array([12.45, 23.67, 45.89, 56.12, 78.95])
print("14. Rounded values:", np.round(prices))


print("----------------------------------------------------------")

# 15. Floor values
arr = np.array([10.2, 15.8, 20.4, 25.9, 30.1])
print("15. Floor values:", np.floor(arr))

print("----------------------------------------------------------")

# 16. Ceiling values
arr = np.array([10.2, 15.8, 20.4, 25.9, 30.1])
print("16. Ceiling values:", np.ceil(arr))


print("----------------------------------------------------------")

# 17. Absolute values
profit = np.array([-5000, 3000, -2500, 4500, -1000])
print("17. Absolute values:", np.abs(profit))


print("----------------------------------------------------------")

# 18. Sort integer array
arr = np.array([45, 12, 89, 34, 67, 23])
print("18. Ascending order:", np.sort(arr))

print("----------------------------------------------------------")

# 19. Sort string array alphabetically
names = np.array(["Ravi", "Anu", "Kiran", "Bala", "Meena"])
print("19. Alphabetical order:", np.sort(names))

print("----------------------------------------------------------")

# 20. Sort in decreasing order using slicing
marks = np.array([78, 45, 92, 66, 88, 54, 99])
print("20. Decreasing order:", np.sort(marks)[::-1])

150
----------------------------------------------------------
2. Minimum: 34
   Maximum: 92
----------------------------------------------------------
3. Average sales: 15200.0
----------------------------------------------------------
4. Variance: 200.0
----------------------------------------------------------
5. Standard deviation: 14.142135623730951
----------------------------------------------------------
6. 50th percentile: 70.0
----------------------------------------------------------
7. 25th percentile: 31250.0
   75th percentile: 43750.0
----------------------------------------------------------
8. Index of highest sales: 3
----------------------------------------------------------
9. Index of lowest temperature: 5
----------------------------------------------------------
10. Base-10 logarithm: [0. 1. 2. 3. 4.]
----------------------------------------------------------
11. Base-2 logarithm: [0. 1. 2. 3. 4. 5.]
----------------------------------------------------------
12. 

In [ ]:
import numpy as np

arr = ([10,20,30,40,50])
np.array(arr)
print(np.sum(arr))

print("-----------------------------------------")

marks = ([45,78,92,56,88,67,34])
np.array(marks)
print(np.max(marks))
print(np.min(marks))

print("------------------------------------------")

sales = np.array([10,20,30,40,50])
print(np.var(sales))

print("-----------------------------------------")

marks = np.array([10,20,30,40,50])
print(np.std(marks))

print("------------------------------------------")

marks = np.array([35,42,55,60,68,72,80,85,95,100])
print(np.percentile(marks,50))

print("------------------------------------------")

sal = ([25000,30000,35000,40000,45000,50000])
print(np.quantile(sal,0.25))
print(np.quantile(sal,0.75))

print("------------------------------------------")

sales = np.array([15000,22000,18000,35000,27000,12000])
print(np.argmax(sales))

print("---------------------------------------------")

temp = np.array([32,28,35,25,30,22,38])
print(np.argmin(temp))

print("-----------------------------------------------")

arr = np.array([1,10,100,1000])
print(np.log10(arr))

print('-----------------------------------------------')

arr = np.array([1,2,4,8,16,32])
print(np.log2(arr))

print("-----------------------------------------------")

arr = np.array([1,2,3,4,5])
print(np.log(arr))

print("-------------------------------------------------")

arr = np.array([4,9,16,25,36,49])
print(np.sqrt(arr))

print("---------------------------------------------------")

prices = np.array([12.45,23.67,45.89,56.12,78.95])
print(np.round(prices))

print("----------------------------------------------------------")

arr = np.array([10.2,15.8,20.4,25.9,30.1])
print(np.floor(arr))

print("------------------------------------------------------------")

print(np.ceil(arr))

print("--------------------------------------------------------------")

profit = np.array([-5000,3000,-2500,4500,-1000])
print(np.abs(profit))

print("------------------------------------------------------------")

arr = np.array([45,12,89,34,67,23])
print(np.sort(arr))

print("-----------------------------------------------------")

names = np.array(["ravi","anu","kiran","bala","meena"])
print(np.sort(names))

print("---------------------------------------------------------------")

marks = np.array([78,45,92,66,88,54,99])
print(np.sort(marks)[::-1]) #for desc order

150
-----------------------------------------
92
34
------------------------------------------
200.0
-----------------------------------------
14.142135623730951
------------------------------------------
70.0
------------------------------------------
31250.0
43750.0
------------------------------------------
3
---------------------------------------------
5
-----------------------------------------------
[0. 1. 2. 3.]
-----------------------------------------------
[0. 1. 2. 3. 4. 5.]
-----------------------------------------------
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
-------------------------------------------------
[2. 3. 4. 5. 6. 7.]
---------------------------------------------------
[12. 24. 46. 56. 79.]
----------------------------------------------------------
[10. 15. 20. 25. 30.]
------------------------------------------------------------
[11. 16. 21. 26. 31.]
--------------------------------------------------------------
[5000 3000 2500 4500 1000]
-----

In [ ]:
import numpy as np

# Q1. Create an array [10,20,30,40,50] and print shape, dimensions, datatype and size.
a = np.array([10,20,30,40,50])
print(a.shape)
print(a.ndim)
print(a.dtype)
print(a.size)
print("--------------------------")


# Q2. Create numbers from 1 to 12 and reshape them into 3x4.
# Also create numbers from 1 to 24 and reshape them into 2x3x4.
b = np.arange(1,13)
print(b.reshape([3,4]))

c = np.arange(1,25)
print(c.reshape([2,3,4]))
print("--------------------------")


# Q3. Create arrays of zeros with shapes 5, 2x2 and 2x6x3.
print(np.zeros(5))
print(np.zeros([2,2]))
print(np.zeros([2,6,3]))
print("--------------------------")


# Q4. Create a 2x3 array of ones and print its values, dimensions and shape.
ar = np.ones([2,3])
print(ar)
print(ar.ndim)
print(ar.shape)
print("--------------------------")


# Q5. Create a 3x4 matrix filled with 7 and a 4x4 identity matrix.
print(np.full([3,4],7))
print(np.eye(4))
print("--------------------------")


# Q6. Generate 5 random numbers and a 2x3 array of random numbers between 0 and 1.
print(np.random.random(5))
print(np.random.random([2,3]))
print("--------------------------")


# Q7. Generate a 3x3 array of random decimal numbers between 10 and 50.
print(np.random.uniform(10,50,[3,3]))
print("--------------------------")


# Q8. Generate a 2x4 array using standard normal distribution.
print(np.random.randn(2,4))
print("--------------------------")


# Q9. Create an array of colors and randomly select 3 colors.
colors = np.array(["Red","Blue","Green","Yellow","Black"])
print(np.random.choice(colors,3))
print("--------------------------")


# Q10. Generate a random integer between 10 and 50 using seed 45.
np.random.seed(45)
ar1 = np.random.randint(10,50)
print(ar1)
print("--------------------------")


# Q11. Generate numbers from 5 to 50 with step 5 using arange.
# Generate 5 equally spaced numbers between 5 and 50 using linspace.
print(np.arange(5,50,5))
print(np.linspace(5,50,5))
print("--------------------------")


# Q12. Shuffle an array and create a permutation of another array.
arr = np.array([10,20,30,40,50,60])
np.random.shuffle(arr)
print(arr)

arr1 = np.array([10,20,30,40,50,60])
r = np.random.permutation(arr1)
print(r)
print("--------------------------")


# Q13. Generate 6 equally spaced numbers between 1 and 100.
print(np.linspace(1,100,6))
print("--------------------------")


# Q14. Create an array from 1 to 12, reshape it into 3x4,
# and convert it back to 1D using ravel().
arr2 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

r1 = np.reshape(arr2,[3,4])
print(r1)

r2 = np.ravel(r1)
print(r2)
print("--------------------------")


# Q15. Create a 2x3 array, print its transpose and convert it to 1D.
arr3 = np.array([[1,2,3],
                 [4,5,6]])

print(arr3.T)

r3 = np.ravel(arr3)
print(r3)
print("--------------------------")


# Q16. Create an array [10,20,30,40,50] with float datatype.
arr4 = np.array([10,20,30,40,50], dtype=float)
print(arr4.dtype)
print(arr4)
print("--------------------------")


# Q17. For the given 2D array:
# 1. Print 50
# 2. Print the last row
# 3. Print the first two columns
# 4. Change 80 to 800
ab = np.array([[10,20,30],
               [40,50,60],
               [70,80,90]])

print(ab[1,1])
print(ab[-1])
print(ab[:,:2])

ab[2,1] = 800
print(ab)
print("--------------------------")


# Q18. Find sum, minimum, maximum and average of the array.
arr5 = np.array([10,20,25,30,50])

print(arr5)
print(sum(arr5))
print(min(arr5))
print(max(arr5))
print(np.average(arr5))
print("--------------------------")


# Q19. For the given marks, find variance, standard deviation,
# 25th percentile, 75th percentile, index of maximum and log10.
marks = np.array([45,56,67,72,81,90,95])

print(np.var(marks))
print(np.std(marks))
print(np.percentile(marks,25))
print(np.percentile(marks,75))
print(np.argmax(marks))
print(np.log10(marks))
print("--------------------------")


# Q20. Perform concatenate, stack and vertical stack on three arrays.
A = np.array([1,2,3])
B = np.array([4,5,6])
C = np.array([7,8,9])

d = np.concatenate([A,B])
print(d)

e = np.stack([A,B], axis=0)
print(e)

g = np.concatenate([A,B,C])
print(g)

f = np.vstack([A,B,C])
print(f)
print("--------------------------")


# Q21. Split a 1D array [1,2,3,4,5,6] into 3 equal parts.
a = np.array([1,2,3,4,5,6])

r = np.split(a,3)
print(r)
print("--------------------------")


# Q22. Split a 1D array at index positions 1 and 4.
r1 = np.split(a,[1,4])
print(r1)
print("--------------------------")


# Q23. Split the following 2D array at row indexes 2 and 3.
b = np.array([[1,2],
              [3,4],
              [5,6],
              [7,8]])

print(np.split(b,[2,3]))
print("--------------------------")


# Q24. Find the number of dimensions of the 2D array.
print(b.ndim)
print("--------------------------")


# Q25. Split the 2D array into 2 equal parts along rows.
print(np.split(b,2,axis=0))
print("--------------------------")

(5,)
1
int64
5
--------------------------
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
--------------------------
[0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]]
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
--------------------------
[[1. 1. 1.]
 [1. 1. 1.]]
2
(2, 3)
--------------------------
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
--------------------------
[0.68599005 0.21897029 0.57273863 0.94997699 0.63016912]
[[0.41145504 0.66241462 0.69048192]
 [0.61191862 0.19975276 0.57073626]]
--------------------------
[[14.1354438  43.50619992 36.74751432]
 [46.92555108 27.80972894 43.22415734]
 [21.0224446  39.50410115 43.32506307]]
--------------------------
[[ 0.20384154  0.84738377 -0.64256725  0.65193438]
 [ 0.01688209 -1.17777099 